
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "codest", email = "thecodest@ya.ru"},
]
dependencies = [
    "djangorestframework>=3.14.0",
    "django>=4.2.3",
]
requires-python = ">=3.11"
license = {text = "MIT"}
